### ISSUE TITLE
Allow conditional rebuilding on specific instances.

### ISSUE THREAD

**Issue by terjekv** [EESSI/eessi-bot-software-layer#157]
If a build fails on one out of five instances, it would be nice to be able to comment something like:

```
@ourbot Please rebuild on instance AWS-broadwell
```

And trigger only that instance to perform the rebuild. See also https://github.com/EESSI/eessi-bot-software-layer/issues/92

**Comment by trz42** [comment]
Issue #93 is somewhat related.

**Comment by boegel** [comment]
@trz42 I think this can be closed, support for `bot: build` commands with filters like `arch:...` was implemented in #172
