### ISSUE TITLE
Improvement for launching script to create tarball from eessi-bot-build.slurm

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#16]
Same here, this can become significantly shorter, I think, by creating a `bot-create-tarball.sh` script that is just being run here (and fed a couple of input variables).

_Originally posted by @boegel in https://github.com/EESSI/eessi-bot-software-layer/pull/10#discussion_r894927012_

**Comment by boegel** [comment]
@trz42 This is actually something for the `software-layer` repo I think, which should provide a build script that the bot can just run.

**Comment by trz42** [comment]
Ah, sure messed up the issues.

**Comment by trz42** [comment]
Replaced by https://github.com/EESSI/software-layer/issues/180
