### ISSUE TITLE
Separate handling of command line arguments

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#25]
`tools/args.py` defines the command line arguments. Currently this is used for two programs where not all arguments are used. Would be good to support different sets of arguments for different programs/tools. In the future, we may add more tools which have other command line arguments.

**Comment by boegel** [comment]
We could have a dedicated `parse_args` function in scripts like `eessi_bot_job_manager.py`.

Maybe there's value in having all options supported by scripts in a separate place, for example a function like `parse_args_job_manager` in `tools/args.py`
