### ISSUE TITLE
The '*' character disappears in results reported by the bot

### ISSUE THREAD

**Issue by casparvl** [EESSI/eessi-bot-software-layer#252]
https://github.com/EESSI/software-layer/pull/467 adds a test step to the build procedure. One of the things it `greps` for is a pattern
`'\[.*FAILED.*\].*Ran .* test case'`. This gets reported in the Details section of the test result, see e.g. [here](https://github.com/EESSI/software-layer/pull/467#issuecomment-1934708438) (unfold the 'SUCCESS' report for the test result). It now says:

> no message matching `[.FAILED.].Ran . test case`

Clearly, the '*' characters have disappeared from this pattern. Likely, they are interpreted by a shell somewhere. I checked the result output file for the test step of this run (`_bot_job5598.test`), and it contained:

```
[TEST]
comment_description = <details><summary>:grin: SUCCESS _(click triangle for details)_</summary><dl><dt>_ReFrame Summary_</dt><dd>[ ESC[32m PASSED ESC[0m ] Ran 5/5 test case(s) from 5 check(s) (0 failure(s), 0 skipped, 0 aborted)</dd><dt>_Details_</dt><dd>:white_check_mark: job output file <code>slurm-5598.out</code><br/>:white_check_mark: no message matching <code>ERROR: </code><br/>:white_check_mark: no message matching <code>\[.*FAILED.*\].*Ran .* test case</code><br/></dd></dl></details>
```
I.e. there, the '*' is still present. The interpretation of the '*' must happen somewhere in the code that takes this report file, and sends it to Github...

**Comment by trz42** [comment]
The '*' character is present. You'll see it when you click on `...` $\rightarrow$ `Edit` in the [comment](https://github.com/EESSI/software-layer/pull/467#issuecomment-1934708438). In that comment I manually added a new line where the code shows what we would have to do to correctly show this.

**Comment by casparvl** [comment]
Ah ok, so it's not interpreted in the bot step, but by Github itself. Hm... not sure how I get those escape characters in there, I guess I'll have to modify the pattern right before writing it to the logfile... A bit hacky, but should work :)

Anyway, issue is not in the bot, so closing this. Thanks!
