### ISSUE TITLE
Directory structure for repository of an EESSI stack

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#3]
We should come up with a directory structure for a repository of an EESSI stack. Assuming we would support several versions of an EESSI stack, e.g., 2021.03, 2021.06, 2021.12, etc, and a complete stack for a single version is defined by one `softwarelist.yaml` easystack file, the directory structure could be as simple as

```
/stacks
- 2021.03
   |- softwarelist.yaml
- 2021.06
   |- softwarelist.yaml
.
.
.
```

If we want to have different stacks for development and production, we could add another directory level or just use a separate repository. The latter would probably better to support different access rights for different stacks.

**Comment by ocaisa** [comment]
You could just ship that with the software, so `.../versions/2021.12/softwarelist.yaml`

**Comment by trz42** [comment]
Sure. Sorry if it was not clear enough what I had in mind. I'm wondering about how we structure the repository where we do pull requests to add new software packages to an EESSI stack. The EESSI bot should then receive an event about the pull request and it may be necessary that the EESSI bot "understands" the structure of that repository to decide whether it shall start working on a pull request or not.

**Comment by trz42** [comment]
Obsolete with #10
