### ISSUE TITLE
Function for identifying PR comment to be updated

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#32]
The bot reports status changes, results, etc as comments back to the PR. For updating these comments it first needs to identify the comment. Currently (as of PR #24) this is based on the contents of the first line in a PR comment (using a job's ID and the app's name which is defined in `app.cfg`). The code is duplicated at some places and should be collected into one function, e.g.,

`def identify_pull_request_comment(pattern: str, repository: str, pr_number: int) -> Tuple[bool, int]:`

which receives a search pattern, a repository name and a pull request number as input and returns a tuple with a return value (`True` - comment found, `False` - no matching comment found) and a number identifying the first comment to be updated (only meaningful if return value is `True`).

**Comment by boegel** [comment]
See (duplicate) code in `process_new_job` and `process_finished_job` in `eessi_bot_job_manager.py`

A dedicated function to this should be added to a new Python module in `tools/github.py`.

Another function to update an existing comment could be created that updates the table in a smarter way.

**Comment by trz42** [comment]
For some other component I use
```python
    def find_comment(self, pull_request, tarball_name):
        """Find comment in pull request that contains name of a tarball.
        Args:
            pull_request (object): PullRequest object (PyGithub) representing
                                   a pull request.
            tarball_name (string): Name of tarball used to identify a comment.
        Returns:
            issue_comment (object): IssueComment object (PyGithub) representing
                                    an issue comment.
        """
        comments = pull_request.get_issue_comments()
        for comment in comments:
            cms = f".*{tarball_name}.*"
            comment_match = re.search(cms, comment.body)
            if comment_match:
                return comment
        return None
