### ISSUE TITLE
get flake8 to pass on all .py files

### ISSUE THREAD

**Issue by boegel** [EESSI/eessi-bot-software-layer#64]
Ideally using a separate PR per Python file

* [x] `connections/github.py`
* [x] `eessi_bot_event_handler.py`
* [x] `eessi_bot_job_manager.py` (see #63)
* [x] `tasks/build.py` (done?)
* [x] `tests/test_eessi_bot_job_manager.py`
* [x] ` tests/test_task_build.py`
* [x] `tools/args.py`
* [x] `tools/config.py`
* [x] `tools/logging.py`

We should also add a code style check in GitHub Actions, cfr. https://github.com/easybuilders/easybuild-framework/blob/develop/.github/workflows/linting.yml

**Comment by trz42** [comment]
All tasks done, all PRs merged. Issue can be closed.
