### ISSUE TITLE
Change method for determining name of user that runs the job manager

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#81]
The job manager uses
```python
username = os.getlogin()
```

See job manager code below where the above is used
https://github.com/EESSI/eessi-bot-software-layer/blob/05716de42efdf5d9c4f3bc1dc8a593ba0fea0160/eessi_bot_job_manager.py#L56

In some cases, for example, when `sudo`ing into a user account (say `newuser`), `os.getlogin()` does not return the expected value. `os.getlogin()` should be replaced by a different method.

**Comment by boegel** [comment]
The easiest thing is probably just grabbing the `$USER` value from the environment, but with a check to make sure it's defined

```python
username = os.getenv('USER', None)
if username is None:
    # report error
