### ISSUE TITLE
Improve start of app (in PyGHee)

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#9]
Currently (PR #4), the following (lines 103-105) is done to start the app

```
app = create_app(klass=EESSIBotSoftwareLayer)
log("EESSI bot for software layer started!")
waitress.serve(app, listen='*:3000')
```

Ideally this should be largely moved to [PyGHee](https://github.com/boegel/PyGHee) which would allow us to move the dependency on `waitress` to PyGHee and then just start the app by something like

`app.start(port=3000)`

**Comment by boegel** [comment]
Also useful would be to print something when the bot was started successfully.
This message should include the location of the log file that the bot is using...
