### ISSUE TITLE
Limit which GH accounts can trigger build jobs

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#97]
Similarly to the deploy step, the build step could be restricted to a configurable list of GH accounts. This would provide an additional protection against running any code on bot instances.

**Comment by boegel** [comment]
See `deploy_permission` in `app.cfg`, which is used in `deploy_built_artefacts` function to check whether GitHub account that added the `bot:deploy` label is allowed to trigger a deploy.

The equivalent should be added for the `build` phase`
